### ISSUE TITLE
Boolean values don't account for errant spaces

### ISSUE THREAD

**Issue by willbarton** [cfpb/wagtail-flags#18]
[The current boolean test](https://github.com/cfpb/wagtail-flags/blob/master/flags/conditions.py#L49-L57) won't succeed if there is a space in the condition value. The test should probably be something to the effect of `'true' in condition.lower()` to provide more latitude in string possibilities. Or it should provide some value validation.

**Comment by chosak** [comment]
Closing this and replacing with https://github.com/cfpb/django-flags/issues/27 as this code was moved to django-flags in #29.
