### ISSUE TITLE
Date comparison fails due to incompatible datetimes

### ISSUE THREAD

**Issue by chosak** [cfpb/wagtail-flags#23]
If you define an `after date` condition [as described in the documentation](https://github.com/cfpb/wagtail-flags#after-date):

```py
# settings.py
FLAGS = {
   'condition': {'after date': '2018-02-01T00:00'}
}
```

The code that tries to make the comparison fails due to this exception:

```py
>>> timezone.now() > dateparse.parse_datetime('2018-02-01T00:00')
Traceback (most recent call last):
  File "<console>", line 1, in <module>
TypeError: can't compare offset-naive and offset-aware datetimes
```

This is because Django's `timezone.now()` returns an `datetime` that is aware of its timezone, but parsing a string like `'2018-02-01T00:00'` doesn't provide the same information.

One simple solution would be to require (and modify documentation to state) that the timestamp string passed in have some offset information, e.g. `'2018-02-01T00:00Z'` or `'2018-02-01T00:00-04:00'`:

```py
>>> timezone.now() > dateparse.parse_datetime('2018-02-01T00:00Z')
True
```

@willbarton how would you feel about this change? Is there some way to enforce this? It feels suboptimal that an error due to misformatted timestamp is hidden and results in a failed check, without any way for the user to know that things are configured wrong.

**Comment by willbarton** [comment]
@chosak I wonder if adding a dependency on something like [dateparser](http://dateparser.readthedocs.io/en/latest/) would make more sense, so that there's more flexibility in the strings.
