### ISSUE TITLE
Split into Wagtail specific and Django Generic

### ISSUE THREAD

**Issue by ldng** [cfpb/wagtail-flags#28]
Hi,

great package that does everything we need. I particularly like that it can be used very early, contrary to most other similar modules.

Any plan on splitting it in 2 modules ? Code looks globally generic plus some specific Wagtail code.
Or would you rather keep it as whole ?

Great work anyhow.
Thanks.

**Comment by willbarton** [comment]
Such a split would be possible... I'm not sure I'd prefer two separate modules though. What we could do is remove the dependency on Wagtail and simply exclude the Wagtail-related features if Wagtail isn't available. That if Wagtail exists, you get the added support for Wagtail Sites, and if it doesn't it still works as a Django feature flag library.  I think we'd also need to update the Django admin to be more consistent with the Wagtail admin.

How's that sound?

**Comment by ldng** [comment]
That would be great !
I'll try to find some time to help on that this weekend :-)

**Comment by willbarton** [comment]
Now that we've got #27 merged I'll start making Wagtail support conditional.

**Comment by willbarton** [comment]
[Django-Flags 3.0.0 has been released!](https://github.com/cfpb/django-flags/releases/tag/3.0.0) and [is on PyPI](https://pypi.org/project/django-flags/)!

Documentation is available here: https://cfpb.github.io/django-flags/
