### ISSUE TITLE
Lack of a request object shouldn't throw an error unless the condition needs it

### ISSUE THREAD

**Issue by Scotchester** [cfpb/wagtail-flags#30]
I was recently prevented from adding a feature flag to a template that renders HTML that eventually is sent out to a PDF because [the rendering](https://github.com/cfpb/cfgov-refresh/blob/master/cfgov/legacy/housing_counselor/generator.py#L129) with basic `template.render` doesn't have a request object. I just wanted to use a Boolean condition, so it didn't matter, in theory, that there was no request object, but the [`flag_enabled` method](https://github.com/cfpb/wagtail-flags/blob/master/flags/templatetags/feature_flags.py#L20) assumes one.

**Comment by willbarton** [comment]
As a workaround you could add a `request` member to the template's context.

**Comment by willbarton** [comment]
Per the [Django-Flags installation docs](https://cfpb.github.io/django-flags/#installation), the request context processor is needed.

[It's already in use for Django templates in cfgov-refresh](https://github.com/cfpb/cfgov-refresh/blob/master/cfgov/cfgov/settings/base.py#L138), but not for Jinja2 templates.

**Comment by Scotchester** [comment]
@willbarton Just to be clear, you're saying that if we [do this](https://github.com/cfpb/cfgov-refresh/compare/jinja2-context-request), then an error won't be thrown in the scenario given in the original post?

**Comment by willbarton** [comment]
@Scotchester yes, I believe so.
