### ISSUE TITLE
Provide frontend cache invalidation on enable/disable

### ISSUE THREAD

**Issue by willbarton** [cfpb/wagtail-flags#40]
The enable/disable button should hook into Wagtail's [frontend cache invalidation](https://docs.wagtail.io/en/v2.6.1/reference/contrib/frontendcache.html) or provide some way to hook in for cache invalidation.

**Comment by willbarton** [comment]
@Scotchester there's no action that makes date-based conditions work. The date is evaluated during the request cycle. If the request doesn't make it to the server because of the frontend cache, the server can't evaluate the flag state and decide it's after a particular date.

boolean conditions are the only ones that have an action performed at some time *before* a request that might evaluate the flag state that could invalidate the cache beforehand.

**Comment by willbarton** [comment]
*Unless* we set date-based conditions only, without time, and rely on the cache expiration. Like, if a flag is set to enable on 9/14/2019, at some point the cache of a page that uses that flag will expire after 9/14/19 and it will fetch a new copy and et viola the flag will be enabled. But we can do that already.

**Comment by willbarton** [comment]
The only alternative for datetime conditions is something like a task scheduler like Celery that would let us schedule invalidations. But again, that would be a solution specific to datetime conditions, and would require specific infrastructure.

**Comment by Scotchester** [comment]
Gotcha, that makes sense. An optional task scheduler configuration does seem like it'd be a useful tool to have in our arsenal.
